id: P007879
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:46:51.318817
source_metadata:
  id: bdr:W21804
  title: གྲོ་ཚང་ས་ཆའི་བག་སྟོན་གྱི་ཆོ་ག་མེ་ཏོག་ཚོམ་བུ།
  author: ''
  volumes:
    feccb087b16c48a3ba0e1d435ab633a9:
      image_group_id: I1KG22771
      title: Volume 1 of gro tshang sa cha'i bag ston gyi cho ga me tog rtsom bu
      volume_number: 1
      total_pages: 110
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
