id: P007879
initial_creation_type: ocr
source_metadata:
  id: bdr:W21804
  title: གྲོ་ཚང་ས་ཆའི་བག་སྟོན་གྱི་ཆོ་ག་མེ་ཏོག་ཚོམ་བུ།
  author: ''
  volumes:
    eb392fd74b474b63bdc684024dc2ded2:
      image_group_id: I1KG22771
      title: ''
      volume_number: 1
      total_pages: 110
ebook_metadata:
  title: གྲོ་ཚང་ས་ཆའི་བག་སྟོན་གྱི་ཆོ་ག་མེ་ཏོག་ཚོམ་བུ།
  author: ''
  sku: P007879
  cover: cover.jpg
  layers:
  - pagination
