id: IA416156A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T06:11:07+00:00'
last_modified: '2022-06-09T06:58:26.939694+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21804
  title: གྲོ་ཚང་ས་ཆའི་བག་སྟོན་གྱི་ཆོ་ག་མེ་ཏོག་ཚོམ་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    84F2:
      image_group_id: I1KG22771
      title: Volume 1 of gro tshang sa cha'i bag ston gyi cho ga me tog rtsom bu
      total_pages: 110
      order: 1
      base_file: 84F2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
